name: 'Delete Neon Project'
description: 'Delete Neon Project using API'

inputs:
  api_key:
    desctiption: 'Neon API key'
    required: true
  project_id:
    desctiption: 'ID of the Project to delete'
    required: true
  api_host:
    desctiption: 'Neon API host'
    default: console.stage.neon.tech

runs:
  using: "composite"
  steps:
    - name: Delete Neon Project
      # Do not try to delete a project if .github/actions/neon-project-create failed before
      if: ${{ inputs.project_id != '' }}
      shell: bash -euxo pipefail {0}
      run: |
        curl \
          "https://${API_HOST}/api/v2/projects/${PROJECT_ID}" \
          --fail \
          --request DELETE \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${API_KEY}"

        echo "Project ${PROJECT_ID} has been deleted"
      env:
        API_HOST: ${{ inputs.api_host }}
        API_KEY: ${{ inputs.api_key }}
        PROJECT_ID: ${{ inputs.project_id }}
