self-hosted-runner:
  labels:
    - arm64
    - dev
    - gen3
    - large
    # Remove `macos-14` from the list after https://github.com/rhysd/actionlint/pull/392 is merged.
    - macos-14
    - small
    - us-east-2
config-variables:
  - REMOTE_STORAGE_AZURE_CONTAINER
  - REMOTE_STORAGE_AZURE_REGION
  - SLACK_UPCOMING_RELEASE_CHANNEL_ID
